image: python:3.13

stages:
  - test

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH'

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  TF_CPP_MIN_LOG_LEVEL: "2"

cache:
  paths:
    - .cache/pip

before_script:
  - python --version
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -e .
  - pip install pytest

lightweight_unit_tests:
  stage: test
  script:
    - bash utests/run_branch_utests.sh
  rules:
    - if: '$CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH != "main" && $CI_PIPELINE_SOURCE != "merge_request_event"'
      when: on_success
    - when: never

baseline_tests:
  stage: test
  script:
    - bash utests/run_mr_utests.sh
  artifacts:
    when: always
    expire_in: 1 month
    name: "baseline_tests_${CI_COMMIT_SHORT_SHA}"
    paths:
      - results/
      - test-reports/
      - "**/models/"
      - "**/cfgs/"
      - "**/logs/"
    reports:
      junit: test-reports/junit.xml
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: on_success
    - when: never