image: python:3.13

stages:
  - test
  - release

workflow:
  rules:
    - if: '$CI_PROJECT_ID != "YOUR_PROJECT_ID_HERE"'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH'
    - if: '$CI_COMMIT_TAG'

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  TF_CPP_MIN_LOG_LEVEL: "2"

cache:
  paths:
    - .cache/pip

before_script:
  - python --version
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -e .
  - pip install pytest

lightweight_unit_tests:
  stage: test
  script:
    - bash utests/run_branch_utests.sh
  rules:
    - if: '$CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH != "main" && $CI_PIPELINE_SOURCE != "merge_request_event"'
      when: on_success
    - when: never

baseline_tests:
  stage: test
  script:
    - bash utests/run_mr_utests.sh
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: on_success
    - when: never

push_to_external_gitlab:
  stage: release
  image: alpine:3.20
  variables:
    GIT_DEPTH: 0
  before_script:
    - apk add --no-cache git
  script:
    - git remote add ext-gitlab "https://${EXT_GITLAB_TOKEN_USER}:${EXT_GITLAB_PUSH_TOKEN}@${EXT_GITLAB_REPO_URL}"
    - git push ext-gitlab HEAD:refs/heads/main
    - git push ext-gitlab "${CI_COMMIT_TAG}"
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+/'
      when: on_success

push_to_github:
  stage: release
  image: alpine:3.20
  variables:
    GIT_DEPTH: 0
  before_script:
    - apk add --no-cache git
  script:
    - git remote add ext-github "https://${EXT_GITHUB_TOKEN_USER}:${EXT_GITHUB_PUSH_TOKEN}@${EXT_GITHUB_REPO_URL}"
    - git push ext-github HEAD:refs/heads/main
    - git push ext-github "${CI_COMMIT_TAG}"
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+/'
      when: on_success